### ISSUE TITLE
[BUG] macOS app not opening

### ISSUE THREAD

**Issue by MateoJohnArgano** [dan0v/AmplitudeSoundboard#46]
**Describe the bug**
App was working a few minutes ago, now it is not working.

**To Reproduce**
No steps to reproduce.

**Expected behavior**
App will not open and will hang

**Screenshots**
https://cleanshot.mateoargano.net/7omYto

**Desktop (please complete the following information):**
 - OS: macOS
 - Version [12.3.1 (21E258)

**Additional context**
N/A

**Comment by dan0v** [comment]
Could you please try opening a Terminal window and running
`cd "[path-to-app]/Amplitude Soundboard.app/Contents/MacOS" && dotnet amplitude_soundboard.dll`. Running this command will require having installed .Net 6 SDK or Runtime, [from Microsoft](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.5-macos-x64-installer). This might show the reason for the hang / crash in your terminal window as the app launches.

**Comment by dan0v** [comment]
Closed as inactive
