### ISSUE TITLE
[BUG] Fails to update if update process is interrupted

### ISSUE THREAD

**Issue by John-Cozy** [dan0v/AmplitudeSoundboard#55]
**Describe the bug**
If the update process is interrupted, the temporary files that are created cannot be overwritten by the updater.

**To Reproduce**
1. Update to a new version, but kill the application before it can finish
2. Try to update it again
3. An error will pop up

**Comment by dan0v** [comment]
Fixed by 2.7.3

**Comment by dan0v** [comment]
@all-contributors please add @swell61 for User Testing
