### ISSUE TITLE
[BUG] Sound clips repeating every other time when "Repeat clip" is toggled on

### ISSUE THREAD

**Issue by scmccall** [dan0v/AmplitudeSoundboard#64]
**Describe the bug**
Sound clips set to "Repeat clip" only repeat every odd replay.
For example, clips will play the first time they're triggered but when that track finishes there will be silence. The UI will still show the clip is playing but no sound is produced. 
When that second repetition shows as completed in the UI, the sound will begin to play for the 3rd repetition. The 4th is then silent, the 5th plays, and so on.

**To Reproduce**
1. Click "Sound Clip List", then "New Sound Clip"
2. Click "Select a file path" and selecting an audio file
3. Toggle "Repeat clip" as checked off 
4. Save the Sound Clip and add it to the Soundboard.
5. Trigger the sound and wait for the sound to finish playing.

**Expected behavior**
When the audio track finishes playing, the track should produce audio for each repetition of the sound.

**Desktop (please complete the following information):**
 - OS: Mac OS Sonoma 14.2.1
 - Version: 2.7.3

**Additional context**
I have tested this with 5 different files of various sizes (from 2.6MB-66.8MB), file types (mp3 and wav), and lengths (14 seconds - 4:17 minutes). I get the same result.
I have tried the typical debugging (restarting program, restarting computer, reinstalling software) with no change in the bug.

**Comment by dan0v** [comment]
@scmccall Thanks for reporting this behavior. It should now be fixed in [Version 2.7.4](https://github.com/dan0v/AmplitudeSoundboard/releases/tag/2.7.4). Please report back if you still see this issue with the new version.
