### ISSUE TITLE
[REQUEST] Start and stop a sound with the same hotkey or GUI thumbnail

### ISSUE THREAD

**Issue by ogmkp** [dan0v/AmplitudeSoundboard#73]
**Is your feature request related to a problem? Please describe.**
When I click on the thumbnail or use a keyboard shortcut to play a sound, and then click on it again, it adds the sound and plays it instantly.

**Describe the solution you'd like**
The ability to set the same trigger to play and stop sound.
The possibility of not duplicating sound playback when it is already playing (in the event of a selection or press a two times the keyboard shortcut).

Thanks !

**Comment by dan0v** [comment]
@ogmkp Thanks for the suggestion! This has been added and merged as a new option in [Version 2.9.0](https://github.com/dan0v/AmplitudeSoundboard/releases/tag/2.9.0).

**Comment by ogmkp** [comment]
Thank you very much !
